name: VelocityEstimationAI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      # Datos y serializacion
      - pandas
      - pyarrow
      - python-dotenv
      - openai
      - pillow
      - pymupdf
      - numpy
      - matplotlib
      - opencv-python
      # Vision y modelos
      - torch
      - torchvision
      - open-clip-torch
      - ultralytics
      - imagededup
      - curl_cffi